# Generated by Django 4.0.3 on 2022-08-09 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_custom_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='custom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predict.custom'),
        ),
    ]
