# Generated by Django 3.2.12 on 2022-08-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_predresults_cosine_sim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='coordi',
            field=models.CharField(default='default', max_length=80),
        ),
    ]
