# Generated by Django 3.2.12 on 2022-08-15 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_wishlist_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='man',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predresults',
            name='woman',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='custom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='predict.custom'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wishlist', to='predict.product'),
        ),
    ]
